//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace MonitorCocinaBackOffice.Module.BusinessObjects
{
	[DefaultClassOptions]
	public partial class Article : XPLiteObject
	{
		int fId;
		[Key(true)]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fName;
		[Size(SizeAttribute.Unlimited)]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		Department fDepartmentId;
		[Association(@"ArticleReferencesDepartment")]
		public Department Department
		{
			get { return fDepartmentId; }
			set { SetPropertyValue<Department>(nameof(Department), ref fDepartmentId, value); }
		}

		XPCollection<Monitor> fmonitors;
		[Association(@"ArticleReferencesMonitor")]
		public XPCollection<Monitor> Monitors
		{
			 get { return GetCollection<Monitor>(nameof(Monitors)); } 
		}
	}

}
