//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace MonitorCocinaBackOffice.Module.BusinessObjects
{

	[DefaultClassOptions]
	public partial class Department : XPLiteObject
	{
		int fId;
		[Key(true)]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fName;
		[Size(SizeAttribute.Unlimited)]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		Family fFamilyId;
		[Association(@"DepartmentReferencesFamily")]
		public Family FamilyId
		{
			get { return fFamilyId; }
			set { SetPropertyValue<Family>(nameof(FamilyId), ref fFamilyId, value); }
		}
		[Association(@"ArticleReferencesDepartment")]
		public XPCollection<Article> Articles { get { return GetCollection<Article>(nameof(Articles)); } }

		//XPCollection<Monitor> fmonitors;
		[Association(@"DepartmentReferencesMonitor")]
		public XPCollection<Monitor> Monitors
		{
			get { return GetCollection<Monitor>(nameof(Monitors)); }
		}

	}

}
