//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MonitorCocinaBackOffice.Module.BusinessObjects
{

	public partial class Order : XPLiteObject
	{
		int fId;
		[Key(true)]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fSoftwareVers;
		[Size(SizeAttribute.Unlimited)]
		public string SoftwareVers
		{
			get { return fSoftwareVers; }
			set { SetPropertyValue<string>(nameof(SoftwareVers), ref fSoftwareVers, value); }
		}
		int fMadiCustNo;
		public int MadiCustNo
		{
			get { return fMadiCustNo; }
			set { SetPropertyValue<int>(nameof(MadiCustNo), ref fMadiCustNo, value); }
		}
		int fCompNo;
		public int CompNo
		{
			get { return fCompNo; }
			set { SetPropertyValue<int>(nameof(CompNo), ref fCompNo, value); }
		}
		int fStoreNo;
		public int StoreNo
		{
			get { return fStoreNo; }
			set { SetPropertyValue<int>(nameof(StoreNo), ref fStoreNo, value); }
		}
		string fOrderId;
		[Size(SizeAttribute.Unlimited)]
		public string OrderId
		{
			get { return fOrderId; }
			set { SetPropertyValue<string>(nameof(OrderId), ref fOrderId, value); }
		}
		int fTermNo;
		public int TermNo
		{
			get { return fTermNo; }
			set { SetPropertyValue<int>(nameof(TermNo), ref fTermNo, value); }
		}
		int fOperNo;
		public int OperNo
		{
			get { return fOperNo; }
			set { SetPropertyValue<int>(nameof(OperNo), ref fOperNo, value); }
		}
		string fOperName;
		[Size(SizeAttribute.Unlimited)]
		public string OperName
		{
			get { return fOperName; }
			set { SetPropertyValue<string>(nameof(OperName), ref fOperName, value); }
		}
		string fTbNum;
		[Size(SizeAttribute.Unlimited)]
		public string TbNum
		{
			get { return fTbNum; }
			set { SetPropertyValue<string>(nameof(TbNum), ref fTbNum, value); }
		}
		int fPax;
		public int Pax
		{
			get { return fPax; }
			set { SetPropertyValue<int>(nameof(Pax), ref fPax, value); }
		}
		string fTableType;
		[Size(SizeAttribute.Unlimited)]
		public string TableType
		{
			get { return fTableType; }
			set { SetPropertyValue<string>(nameof(TableType), ref fTableType, value); }
		}
		DateTime fStartTime;
		public DateTime StartTime
		{
			get { return fStartTime; }
			set { SetPropertyValue<DateTime>(nameof(StartTime), ref fStartTime, value); }
		}
	}

}
