//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MonitorCocinaBackOffice.Module.BusinessObjects
{

	public partial class OrderItem : XPLiteObject
	{
		int fPrintOrderGroupId;
		[Indexed(Name = @"IX_OrderItem_PrintOrderGroupId")]
		public int PrintOrderGroupId
		{
			get { return fPrintOrderGroupId; }
			set { SetPropertyValue<int>(nameof(PrintOrderGroupId), ref fPrintOrderGroupId, value); }
		}
		int fArticleId;
		[Indexed(Name = @"IX_OrderItem_ArticleId")]
		public int ArticleId
		{
			get { return fArticleId; }
			set { SetPropertyValue<int>(nameof(ArticleId), ref fArticleId, value); }
		}
		int fUnits;
		public int Units
		{
			get { return fUnits; }
			set { SetPropertyValue<int>(nameof(Units), ref fUnits, value); }
		}
		string fModifList;
		[Size(SizeAttribute.Unlimited)]
		public string ModifList
		{
			get { return fModifList; }
			set { SetPropertyValue<string>(nameof(ModifList), ref fModifList, value); }
		}
		int fMenuOrderLineNo;
		public int MenuOrderLineNo
		{
			get { return fMenuOrderLineNo; }
			set { SetPropertyValue<int>(nameof(MenuOrderLineNo), ref fMenuOrderLineNo, value); }
		}
		int fStateId;
		[Indexed(Name = @"IX_OrderItem_StateId")]
		public int StateId
		{
			get { return fStateId; }
			set { SetPropertyValue<int>(nameof(StateId), ref fStateId, value); }
		}
		public struct CompoundKey1Struct
		{
			[Persistent("OrderId")]
			public int OrderId { get; set; }
			[Persistent("OrderLineNo")]
			public int OrderLineNo { get; set; }
		}
		[Key, Persistent]
		public CompoundKey1Struct CompoundKey1;
	}

}
