//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using System.Drawing;

namespace MonitorCocinaBackOffice.Module.BusinessObjects
{
	[DefaultClassOptions]
	public partial class State : XPLiteObject
	{
		int fId;
		[Key(true)]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fName;
		[Size(SizeAttribute.Unlimited)]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		int fOrder;
		public int Order
		{
			get { return fOrder; }
			set { SetPropertyValue<int>(nameof(Order), ref fOrder, value); }
		}
		//string fColor;
		//[Size(SizeAttribute.Unlimited)]
		//public string Color
		//{
		//	get { return fColor; }
		//	set { SetPropertyValue<string>(nameof(Color), ref fColor, value); }
		//}

  [Persistent("Color")]
		private Int32 fColor;
		[NonPersistent]
		public Color Color
		{
			get { return Color.FromArgb(fColor); }
			set
			{
				fColor = value.ToArgb();
				OnChanged("Color");
			}
		}

		bool fMarchando;
		public bool Marchando
		{
			get { return fMarchando; }
			set { SetPropertyValue<bool>(nameof(Marchando), ref fMarchando, value); }
		}

		XPCollection<Monitor> fmonitors;
		[Association(@"StateReferencesMonitor")]
		public XPCollection<Monitor> Monitors
		{
			get { return GetCollection<Monitor>(nameof(Monitors)); }
		}
	}

}
